// // /*
// // Auto-generated by: https://github.com/pmndrs/gltfjsx
// // Author: KangaroOz 3D (https://sketchfab.com/KangaroOz-3D)
// // License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
// // Source: https://sketchfab.com/3d-models/macbook-pro-2021-37763335f74b497e91906986b170b5d1
// // Title: MacBook Pro 2021
// // */

// // import React, { useRef } from "react";
// // import { useGLTF } from "@react-three/drei";

// // export function Model(props) {
// //   const { nodes, materials } = useGLTF("/macbook_pro_2021.glb");
// //   return (
// //     <group {...props} dispose={null}>
// //       <group position={[0.121, 0.007, 0]}>
// //         <mesh
// //           castShadow
// //           receiveShadow
// //           geometry={nodes.Object_6.geometry}
// //           material={materials.MacBookPro}
// //         />
// //         <mesh
// //           castShadow
// //           receiveShadow
// //           geometry={nodes.Object_8.geometry}
// //           material={materials.MacBookPro}
// //         />
// //       </group>
// //       <mesh
// //         castShadow
// //         receiveShadow
// //         geometry={nodes.Object_4.geometry}
// //         material={materials.MacBookPro}
// //       />
// //     </group>
// //   );
// // }

// // useGLTF.preload("/macbook_pro_2021.glb");

// // src/components/Model.jsx
// import React from "react";
// import { useGLTF } from "@react-three/drei";

// export function Model(props) {
//   const { nodes, materials } = useGLTF("/models/macbook_pro_2021.glb");

//   return (
//     <group {...props} dispose={null} scale={[6, 6, 6]}>
//       <group position={[0.121, 0.007, 0]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_6.geometry}
//           material={materials.MacBookPro}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_8.geometry}
//           material={materials.MacBookPro}
//         />
//       </group>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Object_4.geometry}
//         material={materials.MacBookPro}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/models/macbook_pro_2021.glb");

/**
 * MacBook Pro 2021 Model (Animated Lid Ready)
 * Author: KangaroOz 3D (https://sketchfab.com/KangaroOz-3D)
 * License: CC-BY-NC-4.0
 * Optimized by: Bhupesh & ChatGPT
 */

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

export const Model16Pro = ({
  animateLid = true,
  scale = [6, 6, 6],
  position = [0, -1.5, 0],
  rotation = [0, 0, 0],
}) => {
  const groupRef = useRef();
  const lidRef = useRef();

  const { nodes, materials } = useGLTF("/models/macbook_pro_2021.glb");

  useEffect(() => {
    if (animateLid && lidRef.current) {
      gsap.to(lidRef.current.rotation, {
        x: -Math.PI / 1.8,
        duration: 2,
        scrollTrigger: {
          trigger: "#macbook-section",
          start: "top center",
          end: "bottom center",
          scrub: true,
        },
      });
    }
  }, [animateLid]);

  return (
    <group
      ref={groupRef}
      dispose={null}
      scale={scale}
      position={position}
      rotation={rotation}
    >
      {/* Lid + Screen */}
      <group ref={lidRef} position={[0.121, 0.007, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.MacBookPro}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.MacBookPro}
        />
      </group>

      {/* Base */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.MacBookPro}
      />
    </group>
  );
};

useGLTF.preload("/models/macbook_pro_2021.glb");
